jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - checkout
            - node/with-cache:
                steps:
                  - run: npm install
            - run:
                name: friends npm setup
                command: |
                  cd friends
                  npm install
                  npm run prestart
                  cd ../
            - run:
                name: presence npm setup
                command: |
                  cd presence
                  npm install
                  npm run prestart
                  cd ../
            - run:
                name: chat npm setup
                command: |
                  cd chat
                  npm install
                  ./protogen.sh
                  npm run prestart
                  npm run-script build
                  cd ../
orbs:
  node: circleci/node@1.1
version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - build
