version: 2.1

orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@0.5.20
  protobuf: izumin5210/protobuf@0.1.0

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: jonathancardoso/building-on-ci
      DOCKER_REGISTRY: lightbend-docker-registry.bintray.io/cloudstate-chat-sample/
    docker:
      - image: circleci/buildpack-deps:stretch'
  node-builder:
    environment:
      IMAGE_NAME: jonathancardoso/building-on-ci
      DOCKER_REGISTRY: lightbend-docker-registry.bintray.io/cloudstate-chat-sample/


commands:
  install_protoc:
    description: "Install Protoc"
    parameters:
      version:
        type: string
        default: "3.11.2"
    steps:
      - run:
          name: "Install protoc"
          command: |
            mkdir -p /tmp/protoc
            cd /tmp/protoc
            wget https://github.com/protocolbuffers/protobuf/releases/download/v<< parameters.version >>/protoc-<< parameters.version >>-linux-x86_64.zip
            unzip protoc*.zip
            sudo mv bin/protoc /usr/local/bin/

jobs:
  build2:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            cd friends
            npm insall
            npm run prestart
            docker build -t $DOCKER_REGISTRY/friends:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  docker-build:
    executor:
      name: node/default
      tag: '13.8.0'
    environment:
      DOCKER_REGISTRY: lightbend-docker-registry.bintray.io/cloudstate-chat-sample
    steps:
      - checkout
      - setup_remote_docker
      - install_protoc
      - node/with-cache:
          cache-key: friends/package.json
          dir: friends/node_modules/
          steps:
            - run:
                name: build friends docker image
                command: |
                  cd friends
                  npm install
                  npm run prestart
                  docker build -t "$DOCKER_REGISTRY"/friends .
                  cd ../
      - node/with-cache:
          cache-key: presence/package.json
          dir: presence/node_modules/
          steps:
            - run:
                name: build presence docker image
                command: |
                  cd presence
                  npm install
                  npm run prestart
                  docker build -t "$DOCKER_REGISTRY"/presence .
                  docker images
                  cd ../
      - node/with-cache:
          cache-key: chat/package.json
          dir: chat/node_modules/
          steps:
            - run:
                name: build chat docker image
                command: |
                  cd chat
                  npm install
                  ./protogen.sh
                  npm run prestart
                  docker build -t "$DOCKER_REGISTRY"/chat .
                  docker images
                  cd ../
      - run:
          name: Archive Docker images
          command: |
            docker svae -o images.tar "$DOCKER_REGISTRY"/friends "$DOCKER_REGISTRY"/presence "$DOCKER_REGISTRY"/chat
      - persist_to_workspace:
          root: .
          paths:
            - ./friends.tar
            - ./presence.tar
            - ./chat.tar

  publish-latest:
    executor:
      name: node/default
      tag: '13.8.0'
    environment:
      DOCKER_IMAGE_TAG: latestu
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: |
            docker images
            #docker load -i /tmp/workspace/friends.tar
            #docker load -i /tmp/workspace/presence.tar
            #docker load -i /tmp/workspace/chat.tar
            docker load -i /tmp/workspace/images.tar
            docker images
      - run:
          name: Publish Docker Images to BinTray
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin lightbend-docker-registry.bintray.io
            # docker login -u srikanth.koneru@lightbend -p "$DOCKERHUB_PASS" lightbend-docker-registry.bintray.io
            docker push "$DOCKER_REGISTRY"/friends:"$DOCKER_IMAGE_TAG"
            docker push "$DOCKER_REGISTRY"/presence:"$DOCKER_IMAGE_TAG"
            docker push "$DOCKER_REGISTRY"/chat:"$DOCKER_IMAGE_TAG"

workflows:
  test:
    jobs:
      - docker-build
      - publish-latest:
          requires:
            - docker-build

#  build-master:
#    jobs:
#      - build:
#          filters:
#            branches:
#              only: master
#      - publish-latest:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
