# Stateful service descriptor for the gateway app
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: chat
spec:
  containers:
  - image: lightbend-docker-registry.bintray.io/cloudstate-samples/chat:latest
    name: chat
