apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    banzaicloud.com/last-applied: '{"metadata":{"labels":{"app":"presence","app.kubernetes.io/component":"user-function","app.kubernetes.io/managed-by":"cloudstate-operator","app.kubernetes.io/name":"presence"},"name":"presence","namespace":"corey-test","ownerReferences":[{"apiVersion":"cloudstate.io/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"StatefulService","name":"presence","uid":"043d7cab-54ca-11ea-a170-4201ac100106"}]},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/component":"user-function","app.kubernetes.io/managed-by":"cloudstate-operator","app.kubernetes.io/name":"presence"}},"strategy":{},"template":{"metadata":{"annotations":{"traffic.sidecar.istio.io/excludeInboundPorts":"2552,8558","traffic.sidecar.istio.io/excludeOutboundPorts":"2552,8558"},"labels":{"app.kubernetes.io/component":"user-function","app.kubernetes.io/managed-by":"cloudstate-operator","app.kubernetes.io/name":"presence"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"8080"}],"image":"coreyauger/presence:latest","imagePullPolicy":"Always","name":"user-function","ports":[{"containerPort":8080,"name":"user-port","protocol":"TCP"}],"resources":{}},{"env":[{"name":"USER_FUNCTION_PORT","value":"8080"},{"name":"REMOTING_PORT","value":"2552"},{"name":"MANAGEMENT_PORT","value":"8558"},{"name":"HTTP_PORT","value":"8013"},{"name":"SELECTOR_LABEL","value":"app.kubernetes.io/name"},{"name":"SELECTOR_LABEL_VALUE","value":"presence"},{"name":"REQUIRED_CONTACT_POINT_NR","value":"1"},{"name":"JAVA_OPTS","value":"-Xms256m
      -Xmx256m"}],"image":"gcr.io/cloudstateengine/cloudstate-proxy-in-memory:47d4f45","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/alive","port":8558,"scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"cloudstate-sidecar","ports":[{"containerPort":8013,"name":"grpc-http-proxy","protocol":"TCP"}],"readinessProbe":{"failureThreshold":5,"httpGet":{"path":"/ready","port":8558,"scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"memory":"512Mi"},"requests":{"cpu":"400m","memory":"512Mi"}},"volumeMounts":[{"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount","name":"service-account-token"}]}],"serviceAccountName":"cloudstate-pod-service-account","volumes":[{"name":"service-account-token","secret":{"secretName":"cloudstate-pod-service-account-token"}}]}}},"status":{}}'
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-02-22T16:04:08Z"
  generation: 1
  labels:
    app: presence
    app.kubernetes.io/component: user-function
    app.kubernetes.io/managed-by: cloudstate-operator
    app.kubernetes.io/name: presence
  name: presence
  namespace: corey-test
  resourceVersion: "62276829"
  selfLink: /apis/extensions/v1beta1/namespaces/corey-test/deployments/presence
  uid: f4f86394-558c-11ea-ba83-4201ac100108
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: user-function
      app.kubernetes.io/managed-by: cloudstate-operator
      app.kubernetes.io/name: presence
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: 2552,8558
        traffic.sidecar.istio.io/excludeOutboundPorts: 2552,8558
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: user-function
        app.kubernetes.io/managed-by: cloudstate-operator
        app.kubernetes.io/name: presence
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: coreyauger/presence:latest
        imagePullPolicy: Always
        name: user-function
        ports:
        - containerPort: 8080
          name: user-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: USER_FUNCTION_PORT
          value: "8080"
        - name: REMOTING_PORT
          value: "2552"
        - name: MANAGEMENT_PORT
          value: "8558"
        - name: HTTP_PORT
          value: "8013"
        - name: SELECTOR_LABEL
          value: app.kubernetes.io/name
        - name: SELECTOR_LABEL_VALUE
          value: presence
        - name: REQUIRED_CONTACT_POINT_NR
          value: "1"
        - name: JAVA_OPTS
          value: -Xms256m -Xmx256m
        image: coreyauger/cloudstate-proxy-in-memory:latest
        args:
          - "-Dakka.io.tcp.trace-logging=on"
          - "-Dorg.slf4j.simpleLogger.defaultLogLevel=debug"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /alive
            port: 8558
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cloudstate-sidecar
        ports:
        - containerPort: 8013
          name: grpc-http-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ready
            port: 8558
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: service-account-token
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cloudstate-pod-service-account
      serviceAccountName: cloudstate-pod-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - name: service-account-token
        secret:
          defaultMode: 420
          secretName: cloudstate-pod-service-account-token
status:
  availableReplicas: 1
  collisionCount: 1
  conditions:
  - lastTransitionTime: "2020-02-22T16:04:20Z"
    lastUpdateTime: "2020-02-22T16:04:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-02-22T16:04:08Z"
    lastUpdateTime: "2020-02-22T16:04:20Z"
    message: ReplicaSet "presence-76d6d6f4f4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
