apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"creationTimestamp":"2020-01-23T20:55:15Z","generation":13,"labels":{"app.kubernetes.io/component":"user-function","app.kubernetes.io/managed-by":"cloudstate-operator","app.kubernetes.io/name":"chat-routes"},"name":"chat-routes","namespace":"corey-test","ownerReferences":[{"apiVersion":"cloudstate.io/v1alpha1","blockOwnerDeletion":true,"controller":true,"kind":"Route","name":"chat-routes","uid":"a7c3d4a4-3e22-11ea-a5c2-4201ac10010a"}],"resourceVersion":"47588953","selfLink":"/apis/networking.istio.io/v1alpha3/namespaces/corey-test/virtualservices/chat-routes","uid":"a7c52781-3e22-11ea-9481-4201ac100108"},"spec":{"gateways":["default"],"hosts":["*"],"http":[{"match":[{"uri":{"prefix":"/cloudstate.samples.chat.friends.Friends/"}}],"name":"friends-routes","request_headers_to_remove":["grpc-accept-encoding"],"route":[{"destination":{"host":"friends.corey-test.svc.cluster.local","port":{"number":80}}}]},{"match":[{"uri":{"prefix":"/cloudstate.samples.chat.presence.Presence/"}}],"name":"presence-routes","route":[{"destination":{"host":"presence.corey-test.svc.cluster.local","port":{"number":80}}}]},{"match":[{"uri":{"prefix":"/"}}],"name":"chat-routes","route":[{"destination":{"host":"chat.corey-test.svc.cluster.local","port":{"number":80}}}]}]}}
    creationTimestamp: "2020-01-23T20:55:15Z"
    generation: 14
    labels:
      app.kubernetes.io/component: user-function
      app.kubernetes.io/managed-by: cloudstate-operator
      app.kubernetes.io/name: chat-routes
    name: chat-routes
    namespace: corey-test
    ownerReferences:
    - apiVersion: cloudstate.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Route
      name: chat-routes
      uid: a7c3d4a4-3e22-11ea-a5c2-4201ac10010a
    resourceVersion: "47590370"
    selfLink: /apis/networking.istio.io/v1alpha3/namespaces/corey-test/virtualservices/chat-routes
    uid: a7c52781-3e22-11ea-9481-4201ac100108
  spec:
    gateways:
    - default
    hosts:
    - '*'
    http:
    - match:
      - uri:
          prefix: /cloudstate.samples.chat.friends.Friends/
      name: friends-routes
      route:
      - destination:
          host: friends.corey-test.svc.cluster.local
          port:
            number: 80
    - match:
      - uri:
          prefix: /cloudstate.samples.chat.presence.Presence/
      name: presence-routes
      route:
      - destination:
          host: presence.corey-test.svc.cluster.local
          port:
            number: 80
    - match:
      - uri:
          prefix: /
      name: chat-routes
      route:
      - destination:
          host: chat.corey-test.svc.cluster.local
          port:
            number: 80
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
